- name: Define the network
  virt_net:
    command: define
    name: "{{ net_name }}"
    xml: '{{ lookup("template", "templates/networks/nat_225.xml.j2") }}'

- name: Create network
  virt_net:
    command: create
    name: "{{ net_name }}"
    state: active


- name: Autostart the network
  virt_net:         
    name: "{{ net_name }}"
    autostart: yes
