- name: kvm network | generate network configuration
  template:
    dest: "{{ role_path }}/files/networks/{{ net.name }}.xml"
    src: templates/networks/nat.xml.j2
  loop: "{{ nat_networks }}"
  loop_control:
    loop_var: net

- name: kvm network | define network
  virt_net:
    command: define
    name: "{{ net.name }}"
    xml: "{{ lookup('file', '{{ role_path }}/files/networks/{{ net.name }}.xml') }}"
  become: true
  loop: "{{ nat_networks }}"
  loop_control:
    loop_var: net

- name: kvm network | create network
  virt_net:
    command: create
    name: "{{ net.name }}"
    state: active
  loop: "{{ nat_networks }}"
  loop_control:
    loop_var: net

- name: kvm network | enable autostart for network
  virt_net:
    name: "{{ net.name }}"
    autostart: yes
  loop: "{{ nat_networks }}"
  loop_control:
    loop_var: net