---
- hosts: localhost
  become: yes

  vars:
    networks:
      - name: routed229
        type: routed
        source_dev: br0
        br_name: virbr229
        cidr: 192.168.229.0/24
        dhcp_cidr: 192.168.229.128/25
      - name: nat222
        type: nat
        br_name: nat222
        cidr: 192.168.222.0/24
        dhcp_cidr: 192.168.222.128/25
      - name: hostbr211
        type: bridge
        source_dev: br0

    pools:
      - name: hostpool
        type: dir
        capacity: 100000000000
        path: /kvmhostpool
      - name: hostpool1
        type: dir
        path: /kvmhostpool1


    
  roles:
    - kvm