---
- hosts: localhost
  become: yes

  vars:
    nat_networks:
      - name: routed225
        source_dev: br0
        br_name: vibr225
        cidr: 192.168.225.0/24
        dhcp_cidr: 192.168.225.128/25
      - name: routed226
        source_dev: br0
        br_name: vibr226
        cidr: 192.168.226.0/24
        dhcp_cidr: 192.168.226.128/25
      - name: routed227
        source_dev: br0
        br_name: vibr227
        cidr: 192.168.227.0/24
        dhcp_cidr: 192.168.227.128/25


  roles:
    - kvm